### ISSUE TITLE
exposedModel is null when using StatesRebuilder subclass

### ISSUE THREAD

**Issue by jhoogstraat** [GIfatahTH/states_rebuilder#114]
I am having some issues where the exposedModel from the StateBuilder builder function always returns null.
I worked around this issue by using `IN.get()`. Is this behaviour desired?
My Code looks like this:

```dart
class QuizViewModel extends StatesRebuilder<QuizViewModel> {
...
}
```

```dart
@override
Widget build(BuildContext context) {
  return Injector(
    inject: [Inject(() => QuizViewModel.newGame(section))],
    builder: (context) => StateBuilder<QuizViewModel>(
      observe: () => IN.get<QuizViewModel>(),
      tag: ['newQuestion', 'quiz_completed'],
      builder: (context, _) {
        print(_);
        ...
      },
    ),
  );
}
```

**Comment by amoslai5128** [comment]
This should be a null return since you didn't give any init value to the observe.
Also, you might not need to extends StatesRebuiler in least version.
For your code, it's a global reactive model, for more detail you can check it out:
https://github.com/GIfatahTH/states_rebuilder/wiki/Global-ReactiveModel-Injector

`
class QuizViewModel {
  // for example
  int num;
  List<String> quiz;
  ....
  Constructor({num, quiz});
}

class XXX_Page extends StatelessWidget {
...
@override
Widget build(BuildContext context) {
  return Injector(
    inject: [Inject(() => QuizViewModel.newGame(section))],
    builder: (context) => StateBuilder<QuizViewModel>(
      //***** I changed the code here, with a initializing setState.  *******
      observe: () => RM.get<QuizViewModel>()..setState{(s) => s = //init value },
      tag: ['newQuestion', 'quiz_completed'],
      builder: (context, _) {
        print(_);
        ...
      },
    ),
  );
}
`
