### ISSUE TITLE
Question about Injector

### ISSUE THREAD

**Issue by Tyxz** [GIfatahTH/states_rebuilder#16]
Hi,
I really appreciate your library. A bit annoying that with every update I need to rewrite my views, but worth it due to the improvements coming with it.
I tried to implement your injectors, but I have now a problem. Probably, due to my lack of understanding:

My Views look like this: `Login -> Timeline -> ... -> Login -> Timeline`
In my Timeline, I use a local Injector only for the Timeline Subtree.
```dart
Injector(
      models: [
        () => TimelineModel(
              viewModel: TimelineViewModel(
                  notchMargin: 6.0,
                  padding: 8.0,
                  buttomBarExpandedHeight: MediaQuery.of(context).size.height -
                      kBottomBarHeight * 2.5),
            )
      ],
      builder: (context) => _Page(),
);

class _Page extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final model = Injector.get<TimelineModel>();
    return StateWithMixinBuilder(
      mixinWith: MixinWith.singleTickerProviderStateMixin,
      initState: (_, __, vsync) => model.initController(
        vsync: vsync,
      ),
      dispose: (_, __, ___) => model.dispose(),
      tag: TimelineTags.scaffold,
      viewModels: [model],
      builder: (_, __) {...}
    );
  }
}
```
The issue is, that when I change from `Timeline` to `Login`, the model is not disposed (intended). But when I route to a new Timeline object, the model exists already and I get a error from the Injector due to that.

Right now I can think of three solutions: 
1. Inject the model globaly and use Injector.getNew when creating a new View. (Possible too much memory needed for many views)
2. Create a singleton Model outside of the Injector (I did it this way in the past, but would prefer to use the Injector approach now)
3. Test if the model exists and create a new Injection otherwise (unclean and hacky)
```dart
    TimelineModel model = Injector.get<TimelineModel>();
    return model == null
    ? Injector(
      models: [
        () => TimelineModel(
              viewModel: TimelineViewModel(
                  notchMargin: 6.0,
                  padding: 8.0,
                  buttomBarExpandedHeight: MediaQuery.of(context).size.height -
                      kBottomBarHeight * 2.5),
            )
      ],
      builder: (context) => _Page(),
    )
        : _Page();
```
The issue with the last solution is, that sometimes it works nicely, but sometimes the model gets disposed and not newly created (odd).

Can someone advise me with a better and cleaner solution to this issue?
How do I implement a factory Injection and a lazy singleton injection as with the get-it library?

**Comment by GIfatahTH** [comment]
I apologize for annoying you with my updates. Actually, each time a new idea pops my head, and because this library is not very known, I give myself the right to change some functionality of this package. But now, I think it is very stable with the exception to some changes I plan to do on the Injector widget. 
If I understand your case, let's say you have two views. From the Login view, you push towards the TimeLine view and from there you pop back to the login view and back forth.
```dart
class Login extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: RaisedButton(
        child: Text("Go to TimeLine"),
        onPressed: () => Navigator.push(
            context, MaterialPageRoute(builder: (context) => TimeLine())),
      ),
    );
  }
}

class TimeLine extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Injector(
      models: [() => TimelineModel()],
      builder: (_) => _Page(),
    );
  }
}

class _Page extends StatelessWidget {
  final model = Injector.get<TimelineModel>();
  @override
  Widget build(BuildContext context) {
    return Center(
      child: RaisedButton(
        child: Text(model.text),
        onPressed: () => Navigator.pop(context),
      ),
    );
  }
}
```
Is this the case?

**Comment by Tyxz** [comment]
Thanks for the quick reply. I am glad to hear about the stability.
I hope I didn't sound ungrateful for your hard work on this plugin. Also, I want to thank you for the well written medium articles. Very helpful.

Back to my problem:
What I do is more like this: 
```dart
class Login extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: RaisedButton(
        child: Text("Go to TimeLine"),
        onPressed: () => Navigator.pushReplacement(
            context, MaterialPageRoute(builder: (context) => TimeLine())),
      ),
    );
  }
}

class AdditionalClasses extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        RaisedButton(
          child: Text("Login"),
          onPressed: () => Navigator.push(
              context, MaterialPageRoute(builder: (context) => Login())),
        ),
        RaisedButton(
          child: Text("back"),
          onPressed: () => Navigator.pop(context),
        ),
      ]
    );
  }
}

class TimeLine extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Injector(
      models: [() => TimelineModel()],
      builder: (_) => _Page(),
    );
  }
}

class _Page extends StatelessWidget {
  final model = Injector.get<TimelineModel>();
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        RaisedButton(
          child: Text(model.text),
          onPressed: () => Navigator.push(
              context, MaterialPageRoute(builder: (context) => Login())),
        ),
        RaisedButton(
          child: Text(model.moreText),
          onPressed: () => Navigator.push(
              context, MaterialPageRoute(builder: (context) => AdditionalClasses())),
        ),
      ]
    );
  }
}
```
So first is the Login page, afterwards the Timeline. 
From the Timeline, it is possible to go to additional pages, but also again to the Login page. 
From Additional pages, one can go back to the Timeline, but also to the Login.
The Login page does always lead to the Timeline.

**Comment by GIfatahTH** [comment]
Injector widget is a statefullWidget. It registers models in the initState() and unregisters them in the dispose() method.

If you are familiar with get_it, it registers all model glabally before calling the main method, and to manage the memory usage of the app, get_it registers singletons as lazy so that they will not be instantiated until needed, but once instantiated they stay active even if no longer needed.

In the Injector world, we do not need the notion of laziness because we can register any model when needed by using the Injector widget in the appropriate node in the widget tree.

The important term here is "appropriate node or place", It is up to you and depending on the context to choose where in the widget tree to stick the Injector widget. Bad choice leads to some errors like we are encountering with your example.

In your example, you choose to put the Injector inside the TimeLine Widget. From the TimeLine widget, you can push to  Login or AdditionalClasses. When you push to Login page the TimeLine widget is not disposed hence the TimelineModel is not unregistered. When you push to TimeLine again the Injector will try to register TimelineModel again which is not allowed.

You have two solutions:
1- To force the TimeLine to be disposed after pushing to another page be using  pushReplacement like this:
```dart
class _Page extends StatelessWidget {
  final model = Injector.get<TimelineModel>();
  @override
  Widget build(BuildContext context) {
    return Column(mainAxisAlignment: MainAxisAlignment.center, children: [
      RaisedButton(
        child: Text(model.text),
        onPressed: () => Navigator.pushReplacement(
            context, MaterialPageRoute(builder: (context) => Login())),
      ),
      RaisedButton(
        child: Text(model.moreText),
        onPressed: () => Navigator.pushReplacement(context,
            MaterialPageRoute(builder: (context) => AdditionalClasses())),
      ),
    ]);
  }
}
```

2- or if you want to use the same instance of TimelineModel you use the Injector before Login widget:
```dart
main() => runApp(App());



class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Injector(
        models: [() => TimelineModel()],
        builder: (_) => Login(),
      ),
    );
  }
}

class Login extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: RaisedButton(
        child: Text("Go to TimeLine"),
        onPressed: () => Navigator.push(
            context, MaterialPageRoute(builder: (context) => TimeLine())),
      ),
    );
  }
}

class AdditionalClasses extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(mainAxisAlignment: MainAxisAlignment.center, children: [
      RaisedButton(
        child: Text("Login"),
        onPressed: () => Navigator.push(
            context, MaterialPageRoute(builder: (context) => Login())),
      ),
      RaisedButton(
        child: Text("back"),
        onPressed: () => Navigator.pop(context),
      ),
    ]);
  }
}

class TimeLine extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return _Page();
  }
}

class _Page extends StatelessWidget {
  final model = Injector.get<TimelineModel>();
  @override
  Widget build(BuildContext context) {
    return Column(mainAxisAlignment: MainAxisAlignment.center, children: [
      RaisedButton(
        child: Text(model.text),
        onPressed: () => Navigator.push(
            context, MaterialPageRoute(builder: (context) => Login())),
      ),
      RaisedButton(
        child: Text(model.moreText),
        onPressed: () => Navigator.push(context,
            MaterialPageRoute(builder: (context) => AdditionalClasses())),
      ),
    ]);
  }
}

class TimelineModel {
  String text = "text: go to ligin";
  String moreText = "moreText : go to additional class";
}
```

Note: note related to Injector:
you can push form login to Timeline and form Timeline to Login infinitely. That means the stack of the route keeps increasing. I do not know if this is a good or bad thing.

**Comment by Tyxz** [comment]
Sorry for my late response, and thank you a lot for this detailed explanation. I think you answered my question and I see my mistake.
Keep up the good work. 👍
