### ISSUE TITLE
setState() to different type does not throw an error

### ISSUE THREAD

**Issue by samuelstroschein** [GIfatahTH/states_rebuilder#183]
Using setState() and passing a different than defined type does neither give a warning in the IDE, nor throw an error during runtime although it should. 

### Reproducing the bug
```Dart
import 'package:states_rebuilder/states_rebuilder.dart';

final Injected<int> intState = RM.inject(() => 0);

void main() {
  print("State before: ${intState.state}");
  // output: "State before: 0"
  intState.setState((_) => "This should throw an error but it does not.");
  print("State after setting it to a String: ${intState.state}");
  // output: "State after setting it to a String: 0"
}
```

#### Expected output:
1. Error in the IDE from Dart that a String is not assignable to an int. 
2. Runtime exception instead of silently failing and keeping the previous value. 

#### Actual output:
SetState failed silently, holds its previous value.

---------------
### Remarks 
Regarding the first expectation, is the problem related to Dart itself that no error is shown in the IDE?  
That the state holds its previous value seems to make sense but it should throw an Exception so that developers are aware of a bug.

**Comment by GIfatahTH** [comment]
Hi @samuelstroschein I really appreciate your contribution.

What you consider to be a bug it isn't, and it's done by design.

states_rebuilder deals with mutable and immutable state. The logic is simple:
- If the callback of setState returns a value of the same type as the state then the state is immutable, and it is processed accordingly.

- If the callback returns a value of another type or a null value, the state is mutable.

Take the simplest counter example:

```dart
class Counter {
int value = 0;

void increment() => value++;
}
```
The increment method returns void (null).

using setState:
```dart
counter.setState((s) => s.increment());
```

If I set setState to throw if the type is different, this simple example won't work.


Immutable state can be mutated using the state getter. In your example:
```dart
intState.state  = "This should throw an error but it does not.";
```
In this case you get an error in the IDE from Dart that a String is not assignable to an int.

**Comment by samuelstroschein** [comment]
Hi @GIfatahTH,
Thanks for replying. 

If I understand correctly, the line 
```Dart
  intState.setState((_) => "This should throw an error but it does not.");
```
does not throw an error because intState might be mutable and thus states rebuilder does not throw an exception because the logic is either it returns the same type `Int`, or it's a mutable state. If it's a mutable state do not perform a type check (as it's void(null)).

If that is correct, then I argue that states_rebuilder should perform a type check of nonetheless except for void (null): 
```Dart
if (newValue is TypeOfOldValue){
   // immutable
} else if (newValue is null){
  // mutable
} else {
   throw Exception("Type mismatch of immutable state")
}
``` 

Related to #184: Is the implicit differentiation of a mutable and immutable state the key reason why states are not allowed to be set to null?

**Comment by GIfatahTH** [comment]
> If that is correct, then I argue that states_rebuilder should perform a type check of nonetheless except for void (null):
if (newValue is TypeOfOldValue){
   // immutable
} else if (newValue is null){
  // mutable
} else {
   throw Exception("Type mismatch of immutable state")
}


I tried your logic and all tests pass.

>Related to #184: Is the implicit differentiation of a mutable and immutable state the key reason why states are not allowed to be set to null?

Yes, It is one of the reasons,  otherwise, when `newValue` is null, I can't predict if the state is immutable so to set it to null and notify listeners, or if it is mutable so to only notify listeners.

**Comment by samuelstroschein** [comment]
> Yes, It is one of the reasons, otherwise, when `newValue` is null, I can't predict if the state is immutable so to set it to null and notify listeners, or if it is mutable so to only notify listeners.

Wouldn't it be a good idea (necessary for #184?) to explicitly state if a state is mutable or immutable? 

Example: 
```Dart
final Injected<Foo>  state = RM.inject(
     () => Foo(),
     immutable: true,
     ...
}

```

**Comment by samuelstroschein** [comment]
_For future readers:_
Why do/did you [GIfatahTH] reject the idea of explicitly defining states as mutable/immutable?

> 1- Because it was my first implementation that I abandoned.
> 2. Because it is verbose and so far the implicit deduction of immutability works well.
> 3. It's a worthless breaking change.

----

@GIfatahTH I assume this issue can be closed as the type check proposed above is implemented and works?
