### ISSUE TITLE
filterTags? 

### ISSUE THREAD

**Issue by gustavobrian** [GIfatahTH/states_rebuilder#261]
Hello, I need to update my project to the new version, but I can't find the change of "filterTags" in the documentation, how is it in this new version? Thank you

 return Container(
      constraints: BoxConstraints(maxWidth: 400.0, maxHeight: MediaQuery.of(context).size.height - 160.0),
    //  color: Colors.red,
      padding: EdgeInsets.only(left: 8.0, right: 8.0),
      child: StateBuilder<UserAuthService>(
        observe: () => modelReactive,
        initState: (_, _model) {
          _model.setState(
            (state) {
              return state.gotoSingIn();
            },

            **filterTags**: ['LoginWidget'],
            // onError: ErrorHandler.showSnackBar,
          );
        },
        tag: ['LoginWidget'],
        builder: (context, model) {
          if (model.state.loginView == LoginView.Login) {
            return const LoginSignIn();
          } else if (model.state.loginView == LoginView.Rescue) {
            return const LoginRescue();
          } else if (model.state.loginView == LoginView.NewUser) {
            return const LoginNewUser();
          } else {
            return const Loading();
          }
        },
      ),
    );
  }

**Comment by GIfatahTH** [comment]
Hi @gustavobrian It's been a long time since I havent read from you.

`filterTags` is deprecated and removed since version 4. You haven't shown interest in keeping it.

Anyway, `filterTags` is used to control which widget to rebuild after a model issues a notification to represent the new state.

I found `filterTags` an antipattern with Flutter, because we can control when to rebuild a widget (notification), but we can never control when not to rebuild a widget.

With the new API, we can better control the rebuild process by using immutable states and  "shouldRebuild" parameter. Please refer to the pinned issue, where you will find simple examples.

**Comment by amoslai5128** [comment]
@gustavobrian  please check out [Wiki Doc](https://github.com/GIfatahTH/states_rebuilder/wiki/on_builder_api), you can find `shouldRebuild:`, it can let you define a condition to rebuild.

**Comment by gustavobrian** [comment]
yes, that's fine... but the people who are using this library and need to update to null safety killed it. You have to reconsider the entire project with the costs that they represent for something that was already working, whether it is the best pattern or not. These variant and destructive updates destroy the project itself, I can no longer consider risking using this solution for future projects. Thanks anyway for the work... but please don't forget about the developers who use it! They could have left a null safatey version with the original methods.

**Comment by gustavobrian** [comment]
your docoumentation:


OnBuilder(
    listenTo: myState,
    // Called whenever myState emits a notification
    builder: () => Text('${counter.state}'),
    sideEffects: SideEffects(
        initState: () => print('initState'),
        onSetState: (snapState) => print('onSetState'),
        onAfterBuild: () => print('onAfterBuild'),
        dispose: () => print('dispose'),
    ),
    shouldRebuild: (oldSnap, newSnap) {
      return true;
    },
    debugPrintWhenRebuild: 'myState',
),


and your code:
  ///Callback to determine whether this StateBuilder will rebuild or not.
  ///
  final bool Function(SnapState<T>? model)? shouldRebuild;

This project should be private so that you. feel free to change everything all the time.
Otherwise, unfortunately, being public, real-world developers can use it...

**Comment by GIfatahTH** [comment]
@gustavobrian Apologize for the hurt I may cause to you, I know breaking changes are not a good thing.

The case of `fitterTags` as I said, I found them antipattern because with flutter you can cause a widget to re-invoke its builder method by calling `setState`, but you can never prevent it from rebuilding itself even if the state it displays changes.

For all other features, I managed to leave them as they are so that the legacy codes continue to work with null safety.

For this reason, I kept `StateBuilder` as it is and created a new widget called `OnBuilder`. In `OnBuilder`, and since it is a new widget, I found it more convenient to expose both the old and the new state for `shouldRebuild` so you can compare them and decide whether to rebuild the widget or not.

What didn't help me is that you wait a long time to show your displeasure against a particular breaking change, although the difference between `shouldRebuild` in `StateBuilder` and `shouldRebuild` in `OnBuilder` is not considered a breaking change.
