### ISSUE TITLE
Question about version 1.0.0

### ISSUE THREAD

**Issue by hyperpanthera** [GIfatahTH/states_rebuilder#9]
First off, nice update. I am migrating my project to the new update now.

However, I am a bit confused.

Do I understand it right?

We wrap the top main widget (for example: our Scaffold pages) in a [BlocProvider] and all the child widgets in [StatesRebuilder] (if required)?

If so then I am doing it right.

**Comment by GIfatahTH** [comment]
`BlocProvider` widget is used to provide your BloC. This is the most common way to provide the Bloc class. It is the same as in BloC pattern and scoped_model and provider packages. it relays on InheritedWidget. 

You can still provide your bloc with 'StatesRebuilder' in this cas you do not have to use `final counterBloc = BlocProvider.of<CounterBloc>(context);` inside the build methods.

```dart
class CounterBloc extends StatesRebuilder {
  int _counter1 = 0;
  int _counter2 = 0;

  int get counter1 => _counter1;
  int get counter2 => _counter2;

  void increment1() {
    // First, increment the counter
    _counter1++;

    // First alternative.
    // Use the ids parameters to enter a list of ids.
    // Widgets with these ids will rebuild to reflect the new counter value.
    rebuildStates(ids: ["myCounter"]);
  }

  void increment2(State state) {
    // First, increment the counter
    _counter2++;

    // First alternative.
    // Use the ids parameters to enter a list of ids.
    // Widgets with these ids will rebuild to reflect the new counter value.
    rebuildStates(states: [state]);
  }
}

// For simplicity I use this method to provide the CounterBloc:
// Declare the counterBloc without instantiating it
//
// NOTE: You can use the InheritedWidget to provide the CounterBloc
CounterBloc counterBloc;



void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // At the top level of our widget tree where we want to provide the CounterBloc to all its children, we create a StateBuilder Widget.
    // We instantiate the counterBloc variable in the initState parameter, and kill it in the dispose parameter.
    return StateBuilder(
      initState: (_) => counterBloc = CounterBloc(),
      dispose: (_) => counterBloc = null,
      builder: (_) => MaterialApp(
            title: 'states_rebuilder Example',
            home: Counter('States_Rebuilder demostration'),
          ),
    );
  }
}
```
For me I prefer the last method because it is easy as well as safe.

**Comment by hyperpanthera** [comment]
Thanks a lot!

**Comment by lab-nit-s** [comment]
I have a complex scenario where I have a ScrollView inside a StateFulWidget. When the scroll reaches the end or the beginning I need to show/hide another widget (Say for previous next).

I did this by doing something like:
```dart
setState(() {
      _isBottomPrevNextVisible = visible;
    });
```

But when I wrap the entire scaffold of the Stateful Widget in concern within a `BlocProvider` widget.
I am facing issue where the `setState` for the Stateful Widget is getting ignored. I think it is mainly because of this code in the `states_rebulder.dart`:

```dart
class _BlocProviderState<T> extends State<BlocProvider> {
  _BlocProvider<T> _blocProvider;
  @override
  void initState() {
    super.initState();
    _blocProvider = _BlocProvider<T>(
      bloc: widget.bloc,
      child: widget.child,
    );
  }

  @override
  Widget build(BuildContext context) {
    return _blocProvider;
  }
}
```

The `_blocProvider` is being created only once in `initState` and hence the child is not getting rebuilt on `setState` again.

To overcome this. I am not using BlocProvider, but directly using the StateBuilder Widget in my try the way we used to do before 1.0.0. And both works fine.

So, what I want to ask, is my understanding correct here about the `_BlocProviderState<T>` ?
